### ISSUE TITLE
No NULL byte at the end of reversed string

### ISSUE THREAD

**Issue by emneo-dev** [UnchartRed/Libib#3]
No NULL byte will be copied at the end of the returned reversed array
https://github.com/UnchartRed/Libib/blob/86cbdfcdec8927921bb4dc4effcaa0ba4f0e51fc/ib/str/ib_revstr.c#L11

**Comment by RedGinor** [comment]
[ADD]
Since i’m using malloc instead of calloc i should’ve added +1 byte to the allocated space.
https://github.com/UnchartRed/Libib/blob/c55ad74403218d24a7e361be57d7187e16fc5667/ib/str/ib_revstr.c#L14 [FIX]
added the last NULL byte
https://github.com/UnchartRed/Libib/blob/c55ad74403218d24a7e361be57d7187e16fc5667/ib/str/ib_revstr.c#L18
